### PR TITLE
Use distanceMarkers:true for default setup

### PR DESCRIPTION
**Pull request by TheGreatRefrigerator**
Using no options to create distanceMarkers results in markers
getting added to every single polyline that is created.
This doesn't work well with other leaflet plugins.
This issue will be fixed with this.

### CODE REVIEW

**Review by adoroszlai — CHANGES_REQUESTED** [review]
Thanks @TheGreatRefrigerator for this PR.  You are right that turning distance markers "off" by default is probably better for using it with other plugins.

If you would like this to be merged, please revert the addition of `package.json`, which references your repo.  Or, if you prefer, I can merge your first commit and close the PR.

**Comment by TheGreatRefrigerator** [comment]
Thanks for the reply.
Could i also adjust the package.json to reference your repo and info instead?
It would be great to be able to install this directly with npm.

If you don't think its a good idead, you can also just merge the first commit and close the PR 👍

**Comment by TheGreatRefrigerator** [comment]
I switched the links to your repo.

**Comment by adoroszlai** [comment]
Thanks @TheGreatRefrigerator for the contribution.

**Pull request merged**
